---
name: "Spotify Import"
guid: "F03D0ADB-289F-4986-BD6F-2468025249B3"
imageUrl: "https://github.com/Viperinius/jellyfin-plugin-spotify-import/raw/master/viperinius-plugin-spotifyimport.png"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "This plugin imports playlists from Spotify."
description: >
  This plugin enables you to import playlists from Spotify to your Jellyfin server automatically.
  It provides a scheduled task that queries a given list of Spotify playlists and tries to recreate them as best as possible in Jellyfin.
category: "Metadata"
owner: "Viperinius"
artifacts:
- "Viperinius.Plugin.SpotifyImport.dll"
- "SpotifyAPI.Web.dll"
changelog: |2-
  # Changelog

  ## [1.0.0.0] - 2023-02-26

  - Initial release

  ### Added

  - Spotify authentication via authorization code / PKCE
  - Generation of missing tracks lists
  - Import of Spotify playlists
