---
name: "Spotify Import"
guid: "F03D0ADB-289F-4986-BD6F-2468025249B3"
imageUrl: "https://github.com/Viperinius/jellyfin-plugin-spotify-import/raw/master/viperinius-plugin-spotifyimport.png"
version: "1.6.0.1"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "This plugin imports playlists from Spotify."
description: >
  This plugin enables you to import playlists from Spotify to your Jellyfin server automatically.
  It provides a scheduled task that queries a given list of Spotify playlists and tries to recreate them as best as possible in Jellyfin.
category: "Metadata"
owner: "Viperinius"
artifacts:
- "Viperinius.Plugin.SpotifyImport.dll"
- "SpotifyAPI.Web.dll"
changelog: |2-
  # Changelog

  ## [1.6.0.1] - 2024-02-27

  (Internal testing release)

  ## [1.6.0.0] - 2024-02-23

  ### Changed

  - Search Jellyfin server for artist instead of individual tracks and narrow track matching down from there
  - Search Jellyfin server using only the first few characters of an artist name to increase chances of finding matches with slightly different names
  - Use all (album) artists from Spotify to check whether a matching artist exists in Jellyfin, not just the first one

  ### Fixed

  - Catch exceptions from Spotify API lib when retrieving users / playlists

  ## [1.5.0.0] - 2023-12-16

  ### Added

  - New switch to control where missing track files are stored
  - Add new matcher to ignore anything in parentheses in track/album/artist names

  ### Fixed

  - Fix Spotify username regex not allowing special characters

  ## [1.4.0.0] - 2023-10-15

  ### Added

  - Auto-migration of plugin configurations from previous plugin versions
  - More verbose logging that can be enabled

  ### Changed

  - Reworked handling of Spotify user IDs to get all their playlists (moved to its own table separate from individual playlist IDs)

  ### Fixed

  - Fix bug in config page that reset all unsaved table row states when adding a new row
  - Fix parsing of Spotify URLs that contain parameters

  ## [1.3.0.0] - 2023-08-13

  ### Added

  - Extend playlist configuration by allowing user IDs as input, which leads to all of their playlists getting imported automatically

  ### Fixed

  - Fix exception if a Spotify track contains no album artists metadata

  ## [1.2.0.0] - 2023-07-01

  ### Added

  - Extend playlist configurability
    - Allow own playlist names
    - Set target owner / user
  - Allow configuration of the track matcher
    - Choose comparison strictness
    - Choose what parts of the metadata get examined / compared

  ## [1.1.1.0] - 2023-05-06

  ### Fixed

  - Fix exception if a Spotify playlist contains "ghost" items / null tracks
  - A missing tracks file is created even though the playlist is not missing any tracks
  - Fix config page not loading values when revisiting without a full page reload

  ## [1.1.0.0] - 2023-04-15

  ### Added

  - New button to delete all generated missing tracks files
  - New option to specify the date format used for missing tracks file names

  ### Fixed

  - A missing tracks file is created even though the playlist is not missing any tracks
  - Fix exception if a song has no artists, album name or album artists set

  ## [1.0.0.0] - 2023-02-26

  - Initial release

  ### Added

  - Spotify authentication via authorization code / PKCE
  - Generation of missing tracks lists
  - Import of Spotify playlists
