---
name: "Spotify Import"
guid: "F03D0ADB-289F-4986-BD6F-2468025249B3"
version: "0.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "This plugin imports playlists from Spotify."
description: >
  This plugin enables you to import playlists from Spotify to your Jellyfin server automatically.
  It provides a scheduled task that queries a given list of Spotify playlists and tries to recreate them as best as possible in Jellyfin.
category: "Metadata"
owner: "Viperinius"
artifacts:
- "Viperinius.Plugin.SpotifyImport.dll"
changelog: >
  changelog
